name: Daily File Generator

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 显式声明写入权限

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main  # 确保与默认分支名称一致
          token: ${{ secrets.PAT || github.token }}

      - name: Generate File
        run: |
          DATE=$(date +"%Y-%m-%d")
          mkdir -p generated_files
          echo "# Report $DATE" > "generated_files/report-$DATE.md"

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: 'generated_files/*'
          commit_message: "Add report ${{ steps.get-date.outputs.date }}"
          token: ${{ secrets.PAT || github.token }}
          branch: main  # 显式指定分支
