name: Generate MD File Daily

on:
  schedule:
    - cron: '0 8 * * *'  # 每天早上 8 点触发任务
  workflow_dispatch:

jobs:
  generate-md-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2

      - name: Generate MD file from template
        run: |
          echo "Generating Markdown file..."
          python -c '
            import jinja2
            import datetime

            # 加载模板文件
            env = jinja2.Environment(loader=jinja2.FileSystemLoader("."))
            template = env.get_template("template.md")

            # 渲染模板内容
            today = datetime.datetime.now()
            content = template.render(date=today.strftime("%Y-%m-%d"))

            # 写入生成的文件
            output_file = f"daily-notes/Summary_{today.strftime('%Y%m%d')}.md"
            with open(output_file, "w") as f:
                f.write(content)
          '

      - name: Commit and push generated file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/
          git commit -m "Generated Markdown file on $(date +'%Y-%m-%d')"
          git push origin HEAD
