name: Daily File Generator

on:
  schedule:
    - cron: '0 0 * * *'  # UTC时间每天0点（北京时间8点）
  workflow_dispatch:

jobs:
  generate-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须的写入权限

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.PAT || github.token }}
          fetch-depth: 0  # 获取完整提交历史

      - name: Generate File from Template
        id: generate
        run: |
          # 设置时间变量
          DATE=$(date +"%Y-%m-%d")
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S %Z")
          
          # 创建目标目录
          mkdir -p generated_files
          
          # 使用模板生成文件
          sed -e "s/{{DATE}}/$DATE/g" \
              -e "s/{{TIMESTAMP}}/$TIMESTAMP/g" \
              templates/template.md > "daily-notes/Summary-$DATE.md"
          
          # 输出变量供后续步骤使用
          echo "date=$DATE" >> $GITHUB_OUTPUT

      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: 'generated_files/*'
          commit_message: "Auto-generated report for ${{ steps.generate.outputs.date }}"
          token: ${{ secrets.PAT || github.token }}
          branch: main
          committer_name: "Docs Bot"
